version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8991:8991"
    environment:
      - PASSWORD=example1234
    volumes:
      - "./data:/app/data"